export interface Scripture {
  reference: string;
  verse: string;
  /** How David naturally introduces this verse */
  davidIntro: string;
  /** Brief meaning — 1–2 sentences plain language */
  davidReflection: string;
}

export interface MoodData {
  key: string;
  label: string;
  /** David's natural reaction lines before scripture */
  davidReaction: string[];
  /** Natural follow-up questions after scripture */
  davidFollowUps: string[];
  scriptures: Scripture[];
}

export const MOODS_DATA: MoodData[] = [
  {
    key: 'ANXIOUS',
    label: 'Anxious',
    davidReaction: [
      "mm… anxiety will wear somebody down after a while.",
      "yeah… when the mind won't slow down, it's exhausting.",
      "that kind of worry has a way of spreading into everything.",
      "anxiety has a way of making small things feel enormous.",
      "yeah… your mind's probably running through every version of this, huh.",
      "that racing feeling is rough. hard to switch off once it starts.",
      "man… anxious thoughts love to multiply if you let them sit too long.",
      "okay… that's a lot of what-ifs to be carrying at once.",
      "hm. anxiety's convincing even when it's wrong about what's coming.",
      "yeah, that tight chest feeling — I know that one.",
      "worry's exhausting work, even though it doesn't look like work from the outside.",
      "your body's probably as tired as your mind is right now.",
      "that spiral is real. it doesn't feel optional when you're in it.",
      "yeah… the waiting is sometimes worse than whatever you're waiting for.",
      "anxious brains are loud brains. that's not a character flaw, by the way.",
      "sounds like you've been bracing for something for a while now.",
    ],
    davidFollowUps: [
      "has it been stress mostly… or just life piling up?",
      "is there something specific driving it, or just everything at once?",
      "how long have you been feeling like this?",
      "yeah… you been able to sleep okay?",
      "what's the worst-case thought that keeps showing up?",
      "is it one specific thing, or does it keep moving targets?",
      "when did you first notice it creeping in today?",
      "has anything actually helped quiet it down before?",
      "is your body feeling it too — tight chest, that kind of thing?",
      "what usually sets it off for you?",
      "are you able to eat and sleep through it, or is it messing with that too?",
      "is this a today thing or has it been building for a while?",
      "what would it feel like if it actually got quieter?",
      "who else knows you're carrying this right now?",
      "does talking about it help, or does it make it louder?",
      "what's underneath the worry, you think?",
    ],
    scriptures: [
      {
        reference: 'Philippians 4:6-7',
        verse: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.',
        davidIntro: "there's actually a verse people come back to a lot when life starts feeling loud like that…",
        davidReflection: "I think people hold onto it because it doesn't tell you to stop feeling anxious. it just says you don't have to carry it alone.",
      },
      {
        reference: '1 Peter 5:7',
        verse: 'Cast all your anxiety on him because he cares for you.',
        davidIntro: "there's a short one from Peter I think about sometimes…",
        davidReflection: "only seven words but they land heavy. cast it. like you're putting something down you were never supposed to carry alone.",
      },
      {
        reference: 'Matthew 6:34',
        verse: 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.',
        davidIntro: "Jesus actually said something about this once…",
        davidReflection: "it's almost practical. like — just today. that's all. don't borrow trouble from tomorrow.",
      },
      {
        reference: 'Isaiah 41:10',
        verse: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.',
        davidIntro: "there's a verse in Isaiah that's stayed with me…",
        davidReflection: "it's not 'you'll be okay.' it's more like — I've got you. that's the whole thing.",
      },
    ],
  },
  {
    key: 'SAD',
    label: 'Sad',
    davidReaction: [
      "mm… sadness can sit on you for a while.",
      "yeah… sadness has a weight to it that's hard to explain to people who aren't in it.",
      "man… that kind of sadness doesn't just go away on its own, does it.",
      "yeah… sometimes things just feel gray for a while.",
      "that's a heavy kind of tired, the sad kind.",
      "yeah. some days just feel harder to get through than others.",
      "sounds like it's been sitting on your chest a while.",
      "mm… I'm sorry. that's a rough place to be in.",
      "sadness has its own gravity. it pulls at everything else too.",
      "that's real. you don't have to explain it away.",
      "yeah… some things just hurt, plain and simple.",
      "sounds like today's been one of the harder ones.",
      "that low feeling doesn't need a reason to be valid.",
      "man, that's a lot to be sitting with quietly.",
      "yeah… I hear the tiredness in that.",
      "some sadness doesn't have a clean edge to it. it just is.",
    ],
    davidFollowUps: [
      "what happened?",
      "how long have you been feeling this way?",
      "is there something specific, or just a heaviness that's been there?",
      "yeah… you been holding that in for a while?",
      "has it been like this for a few days, or longer?",
      "is there a specific thing under it, or is it more general?",
      "what's today looked like?",
      "are you around people, or have you been pulling back?",
      "what usually helps, even a little?",
      "is this new, or does it come and go?",
      "have you been able to cry, or does it just sit there?",
      "what's the heaviest part of it right now?",
      "did something happen, or has it just been building?",
      "you eating okay through this?",
      "is anyone checking in on you?",
      "what would today look like if it felt a little lighter?",
    ],
    scriptures: [
      {
        reference: 'Psalm 34:18',
        verse: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.',
        davidIntro: "there's a line in Psalms I think about sometimes when things get heavy…",
        davidReflection: "I think people hold onto that one because it doesn't rush them. it just says God is near.",
      },
      {
        reference: 'Matthew 5:4',
        verse: 'Blessed are those who mourn, for they will be comforted.',
        davidIntro: "there's something Jesus said that I keep coming back to…",
        davidReflection: "not 'you'll stop mourning.' just — you will be comforted. that grief isn't invisible.",
      },
      {
        reference: 'Psalm 147:3',
        verse: 'He heals the brokenhearted and binds up their wounds.',
        davidIntro: "there's a verse in Psalms that feels like it was written for exactly this…",
        davidReflection: "binds up wounds — like tending to something carefully. not rushing it. actually tending to it.",
      },
      {
        reference: 'John 16:22',
        verse: 'So with you: Now is your time of grief, but I will see you again and you will rejoice, and no one will take away your joy.',
        davidIntro: "Jesus said something to his disciples once that I think about in moments like this…",
        davidReflection: "he didn't skip the grief. he just said — it won't always be this. that's not nothing.",
      },
    ],
  },
  {
    key: 'LONELY',
    label: 'Lonely',
    davidReaction: [
      "mm… loneliness gets loud sometimes.",
      "yeah… that kind of alone is different from just being by yourself.",
      "loneliness has a way of making everything feel farther away.",
      "man… sometimes you can be surrounded by people and still feel completely alone.",
      "yeah… that ache is real, even when nobody else can see it.",
      "loneliness is sneaky. it convinces you you're the only one who feels it.",
      "mm. that's a hard kind of quiet to sit in.",
      "sounds like you've been carrying that by yourself for a while.",
      "yeah, isolation does something to how you see everything else too.",
      "that distance feeling is rough, even when people are right there.",
      "man… wanting connection and not having it is its own kind of pain.",
      "loneliness doesn't care how many people are in the room.",
      "that's a heavy kind of empty.",
      "yeah… feeling unseen is exhausting in a way that's hard to explain.",
      "mm, that's real. being alone and being lonely aren't even the same thing.",
      "sounds like you've been missing something you can't quite name.",
    ],
    davidFollowUps: [
      "is it a specific kind of lonely… or just everything feeling far away?",
      "have you been able to talk to anyone about it?",
      "yeah… how long has it felt like that?",
      "is there someone you wish was closer?",
      "is it that you're physically alone, or more that you feel unseen?",
      "when did it start feeling like this?",
      "is there anyone you used to be closer to?",
      "what does a good day look like for you, connection-wise?",
      "have you reached out to anyone lately, or has it felt too hard?",
      "is this new, or has it followed you for a while?",
      "what's the hardest part of the day, usually?",
      "do you have people around, even if it doesn't feel like enough?",
      "what would it look like to feel a little less alone this week?",
      "is it a specific person you're missing?",
      "how's your sleep been through all this?",
      "what usually helps, even just a little?",
    ],
    scriptures: [
      {
        reference: 'Psalm 34:18',
        verse: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.',
        davidIntro: "there's a line in Psalms that comes to mind when people feel that kind of alone…",
        davidReflection: "close to the brokenhearted. not watching from far away. close.",
      },
      {
        reference: 'Matthew 28:20',
        verse: 'And surely I am with you always, to the very end of the age.',
        davidIntro: "one of the last things Jesus said to his disciples was…",
        davidReflection: "always. not 'when you're doing well.' not 'when you get it together.' always.",
      },
      {
        reference: 'Isaiah 43:1',
        verse: 'Do not fear, for I have redeemed you; I have summoned you by name; you are mine.',
        davidIntro: "there's a verse in Isaiah that kind of stops you when you read it…",
        davidReflection: "summoned by name. not as a number. by name. that means something.",
      },
      {
        reference: 'Deuteronomy 31:6',
        verse: 'Be strong and courageous. Do not be afraid or terrified, for the Lord your God goes with you; he will never leave you nor forsake you.',
        davidIntro: "there's a promise that shows up more than once in the Bible…",
        davidReflection: "never leave, never forsake. those are pretty strong words. not 'probably' or 'mostly.' never.",
      },
    ],
  },
  {
    key: 'GUILTY',
    label: 'Guilty',
    davidReaction: [
      "mm… guilt gets loud, doesn't it. it replays things.",
      "yeah… carrying something like that wears on a person.",
      "man… shame has a way of telling you it's permanent. it isn't.",
      "yeah… regret can sit heavy long after everyone else has moved on.",
      "mm. guilt loves to replay the same scene over and over.",
      "yeah… that's a heavy thing to keep carrying alone.",
      "shame's a liar about a lot of things, including how permanent it is.",
      "that kind of regret doesn't go away just because time passes.",
      "man… it takes something to even say that out loud.",
      "yeah, guilt has a way of getting louder the more you try to ignore it.",
      "sounds like you've been hard on yourself about this for a while.",
      "mm… that's a lot of weight to be holding by yourself.",
      "yeah… the mind can be a rough courtroom sometimes.",
      "that's real. doesn't mean it defines you though.",
      "guilt gets things wrong sometimes — makes you the worst version of the story.",
      "man… I hear how much this has been sitting with you.",
    ],
    davidFollowUps: [
      "is this about something recent, or something you've been carrying a while?",
      "have you been able to say it out loud to anyone before now?",
      "yeah… what does the guilt keep telling you?",
      "do you feel like it's something God is holding against you… or something you're holding against yourself?",
      "is this something recent, or older than that?",
      "have you told anyone else about this?",
      "do you think you'd judge someone else this harshly for the same thing?",
      "is there something you feel like you need to do about it?",
      "who do you feel like you let down the most?",
      "has this been eating at you for a while now?",
      "what would it take for you to actually let this go?",
      "is this about something you did, or something you didn't do?",
      "do you feel like you've already been forgiven, or still waiting to feel it?",
      "what's the story you keep telling yourself about this?",
      "has anyone actually said they're upset, or is this mostly in your head?",
      "what do you wish you could go back and change?",
    ],
    scriptures: [
      {
        reference: 'Romans 8:1',
        verse: 'Therefore, there is now no condemnation for those who are in Christ Jesus.',
        davidIntro: "there's a line at the start of Romans 8 that I keep coming back to for exactly this…",
        davidReflection: "no condemnation. it doesn't say no consequences or no memories — it says the verdict of condemned is gone. the guilt can be loud, but it isn't the final voice.",
      },
      {
        reference: '1 John 1:9',
        verse: 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.',
        davidIntro: "there's a promise in 1 John that's almost startlingly simple…",
        davidReflection: "faithful and just to forgive. not reluctant. not keeping score. saying it honestly is the whole doorway.",
      },
      {
        reference: 'Psalm 103:12',
        verse: 'As far as the east is from the west, so far has he removed our transgressions from us.',
        davidIntro: "there's a picture in Psalm 103 that's stayed with me…",
        davidReflection: "east and west never meet. that's the distance. the thing you keep replaying — God isn't replaying it.",
      },
      {
        reference: 'Micah 7:19',
        verse: 'You will again have compassion on us; you will tread our sins underfoot and hurl all our iniquities into the depths of the sea.',
        davidIntro: "there's a verse in Micah with an image that's hard to forget…",
        davidReflection: "hurled into the depths of the sea. not filed away to bring up later. gone. the question is whether you'll let yourself stop diving for it.",
      },
    ],
  },
  {
    key: 'STRESSED',
    label: 'Stressed',
    davidReaction: [
      "yeah… stress has a way of stacking up until everything feels urgent.",
      "mm… when everything is pulling at you at once, it's hard to breathe.",
      "man… that kind of pressure wears on a person over time.",
      "yeah… sounds like your mind hasn't had much room to rest.",
      "yeah, that's a lot of plates spinning at once.",
      "mm. sounds like you haven't had a real minute to exhale.",
      "stress like that just keeps compounding if nothing lets up.",
      "man, that pace sounds unsustainable, honestly.",
      "yeah… everything feeling urgent at the same time is its own kind of exhausting.",
      "sounds like you're running on fumes a little.",
      "that's a lot of pressure from a lot of directions.",
      "mm… your nervous system's probably tired of being on alert.",
      "yeah, when does this actually let up for you?",
      "that's the kind of stress that sneaks into your sleep too.",
      "man… sounds like you haven't stopped moving in a while.",
      "yeah… too much, too fast, not enough room to breathe.",
    ],
    davidFollowUps: [
      "is it work, or is it more personal than that?",
      "yeah… how long have you been running at this pace?",
      "what's the thing weighing heaviest right now?",
      "you getting any time to just stop?",
      "what's the biggest thing on your plate right now?",
      "when's the last time you actually had a day off?",
      "is this work stress, or is it more than that?",
      "what would it take to get even a little breathing room?",
      "how's your sleep been through all this?",
      "is there anything you can hand off, even temporarily?",
      "what's the deadline that's weighing heaviest?",
      "are you able to eat regular meals through all this?",
      "who's helping you carry any of this?",
      "what happens if you just... stop for an hour?",
      "is it one big thing, or a hundred small things?",
      "how long has it felt like this?",
    ],
    scriptures: [
      {
        reference: 'Matthew 11:28-30',
        verse: 'Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.',
        davidIntro: "there's something Jesus said that I keep coming back to when life gets like this…",
        davidReflection: "he's not asking you to try harder. he's saying come as you are, put it down for a minute.",
      },
      {
        reference: 'Psalm 55:22',
        verse: 'Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken.',
        davidIntro: "there's a verse in Psalms that comes to mind…",
        davidReflection: "cast your cares — like something you're actually handing over. not just hoping it gets lighter. giving it.",
      },
      {
        reference: 'Exodus 14:14',
        verse: 'The Lord will fight for you; you need only to be still.',
        davidIntro: "one verse that's short but it lands hard…",
        davidReflection: "you need only to be still. that's the hard part when you're stressed — being still feels like failing. but sometimes it's the right move.",
      },
    ],
  },
  {
    key: 'OVERWHELMED',
    label: 'Overwhelmed',
    davidReaction: [
      "yeah… when it all piles up at once, it's hard to know where to even start.",
      "mm… overwhelmed is its own kind of exhaustion.",
      "man… sometimes the weight of everything hits you all at once.",
      "yeah… that feeling of too much and not enough at the same time.",
      "yeah, that's a lot to be holding all at once.",
      "mm… sounds like everything decided to happen in the same week.",
      "man, when it all lands together like that, it's hard to think straight.",
      "that's the kind of overwhelmed where you don't even know what to tackle first.",
      "yeah… too much coming at you from too many directions.",
      "sounds like you're underwater a little right now.",
      "mm, that's a heavy load for one person to carry.",
      "yeah, everything feeling urgent at once is exhausting in a specific way.",
      "man… sounds like you haven't had a second to catch your breath.",
      "that's real. it's okay that you don't have it all figured out right now.",
      "yeah… when it's everything at once, even small things feel impossible.",
      "sounds like your plate got way too full, way too fast.",
    ],
    davidFollowUps: [
      "what's been the biggest thing pressing on you?",
      "yeah… has it been building for a while, or did something tip it over?",
      "how are you doing physically through all of this?",
      "is there one thing — if it shifted — that would give you some room?",
      "if you had to pick just one thing to deal with first, what would it be?",
      "what's making the noise loudest right now?",
      "is there anything on your list that could just... wait?",
      "who could you ask for help with any of this?",
      "how long has it been piling up?",
      "what would it feel like to put one thing down?",
      "is this mostly practical stuff, or emotional too?",
      "what happens if something doesn't get done today?",
      "are you sleeping through any of this?",
      "what's the one thing that would actually help right now?",
      "did something specific tip it over, or has it been building?",
      "how are you doing, underneath all of it?",
    ],
    scriptures: [
      {
        reference: 'Psalm 61:2',
        verse: 'From the ends of the earth I call to you, I call as my heart grows faint; lead me to the rock that is higher than I.',
        davidIntro: "there's a line in Psalms I think about when everything feels like too much…",
        davidReflection: "lead me to the rock that is higher than I. sometimes you just need something solid to stand on when you can't find your footing.",
      },
      {
        reference: '2 Corinthians 12:9',
        verse: 'My grace is sufficient for you, for my power is made perfect in weakness.',
        davidIntro: "Paul writes about this in Corinthians — something God said to him when he was at his lowest…",
        davidReflection: "made perfect in weakness. not in spite of it. in it. that's a different way of looking at this.",
      },
      {
        reference: 'Isaiah 40:31',
        verse: 'But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.',
        davidIntro: "there's a verse in Isaiah that people have been holding onto for centuries…",
        davidReflection: "renew their strength. not infinite energy — renewed. like something that gets restored when you stop trying to run on empty.",
      },
    ],
  },
  {
    key: 'HOPELESS',
    label: 'Hopeless',
    davidReaction: [
      "man… when it gets to that place, it's hard to see past it.",
      "yeah… hopelessness has a way of making the future disappear.",
      "mm… that's a heavy place to be sitting in.",
      "yeah… when it feels like nothing is going to change — that's a particular kind of tired.",
      "mm… I'm really glad you told me that.",
      "yeah… that's a hard place to be honest about.",
      "man, when it feels like nothing's going to shift, that's exhausting in a deep way.",
      "yeah… I hear how heavy that is.",
      "that's real. thank you for saying it out loud instead of carrying it alone.",
      "mm. that kind of dark doesn't lift just because someone tells you to hope.",
      "yeah… feeling like nothing matters is a genuinely hard place to sit in.",
      "man… I'm sitting right here with you in this.",
      "that's a lot to be feeling. I don't want to rush past it.",
      "yeah… I hear you, and I'm not going anywhere.",
      "mm… that's real pain, not just a bad mood.",
      "yeah. I take that seriously — thank you for telling me.",
    ],
    davidFollowUps: [
      "how long have you been feeling like this?",
      "is there something specific that brought you to this point?",
      "yeah… are you safe right now?",
      "has it felt this dark before?",
      "is there anyone in your life who knows how heavy this has gotten?",
      "has it felt like this before, or is this new?",
      "what's today actually looked like?",
      "is there anything, even small, that's felt okay recently?",
      "how long has it felt this dark?",
      "who's someone you trust that you could talk to about this?",
      "did something specific bring this on, or has it built slowly?",
      "what would it mean to you to have someone sit with you through this?",
      "is there a person nearby you'd feel comfortable calling right now?",
      "what's been the hardest part of today?",
      "have you been able to tell anyone else how heavy this feels?",
      "is there anything at all that's felt steady lately?",
    ],
    scriptures: [
      {
        reference: 'Jeremiah 29:11',
        verse: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.',
        davidIntro: "there's a verse — Jeremiah 29:11 — that people in dark seasons come back to…",
        davidReflection: "it's not a quick fix. it's more like a light you can barely see, but it's there. plans for a future and a hope — that was said to people who had lost almost everything.",
      },
      {
        reference: 'Lamentations 3:22-23',
        verse: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
        davidIntro: "there's something in Lamentations — a book literally written in grief — that still manages to say this…",
        davidReflection: "new every morning. the person who wrote that was in ruins. and they still said it. that's not nothing.",
      },
      {
        reference: 'Romans 8:38-39',
        verse: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God.',
        davidIntro: "Paul writes something in Romans that kind of takes your breath away…",
        davidReflection: "nothing in all creation. that's a wide list. and it still ends the same way — nothing. you can't fall far enough out of it.",
      },
    ],
  },
  {
    key: 'GRIEVING',
    label: 'Grieving',
    davidReaction: [
      "mm… grief is its own world. it doesn't move on anyone else's schedule.",
      "yeah… loss has a way of sitting with you even when everything else keeps moving.",
      "man… I'm sorry. that kind of pain is real.",
      "yeah… grief changes you. there's no way around it.",
      "mm. I'm really sorry you're carrying this.",
      "yeah… loss doesn't follow a schedule, no matter what anyone tells you.",
      "man, that kind of absence changes the shape of everything for a while.",
      "yeah… grief shows up in strange moments, doesn't it.",
      "that's real pain. I'm not going to rush you through it.",
      "mm… some days it's quiet, some days it's not. that's normal.",
      "yeah, losing someone rearranges things you didn't expect it to touch.",
      "man… I'm glad you're talking about it instead of carrying it silently.",
      "grief doesn't really end, it just changes shape over time.",
      "yeah… that kind of missing someone doesn't have an expiration date.",
      "mm, I'm sorry. that's a real loss, not something to just move past.",
      "yeah… it makes sense that this still hits you the way it does.",
    ],
    davidFollowUps: [
      "how long has it been?",
      "were you close?",
      "yeah… have you had people around you through this?",
      "what's the hardest part right now?",
      "do you want to tell me about them?",
      "is there a particular moment that keeps coming back to you?",
      "who's been around for you through this?",
      "are the anniversaries and little reminders the hardest part?",
      "how are you sleeping through all this?",
      "is there anything that's helped, even a little?",
      "what do you miss most, on the hard days?",
      "were you able to say what you needed to say to them?",
      "is grief hitting you in waves, or more constant than that?",
      "what's today been like?",
      "do you have people checking in on you regularly?",
      "what would it mean to you if someone just sat with you in this?",
    ],
    scriptures: [
      {
        reference: 'Psalm 34:18',
        verse: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.',
        davidIntro: "there's a line in Psalms that feels like it was written for exactly this…",
        davidReflection: "close to the brokenhearted. not watching from a distance. close.",
      },
      {
        reference: 'Revelation 21:4',
        verse: 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.',
        davidIntro: "there's a promise at the end of Revelation that I come back to…",
        davidReflection: "every tear. not some. every one. that's the end of the story. and knowing that doesn't erase the grief now — but it means this isn't the final word.",
      },
      {
        reference: 'John 11:35',
        verse: 'Jesus wept.',
        davidIntro: "you know the shortest verse in the Bible?",
        davidReflection: "Jesus wept. at Lazarus's tomb. he knew he was about to raise him — and he still cried. grief isn't weakness. even Jesus sat in it.",
      },
    ],
  },
  {
    key: 'ANGRY',
    label: 'Angry',
    davidReaction: [
      "yeah… anger usually means something real underneath it.",
      "mm… some things deserve to make you angry.",
      "man… yeah. I hear that.",
      "yeah… anger doesn't come out of nowhere.",
      "yeah, that sounds like it would make anyone angry.",
      "mm. that's a legitimate thing to be upset about.",
      "man, I don't blame you for being angry about that.",
      "yeah… that kind of thing should make you angry, honestly.",
      "sounds like this has been building for a while.",
      "mm… you're allowed to be angry about this. no need to justify it to me.",
      "yeah, that's a real reason to be upset.",
      "man… that would frustrate anybody.",
      "yeah… I can hear how much that got under your skin.",
      "sounds like that crossed a real line for you.",
      "mm, that's fair. some things deserve exactly that reaction.",
      "yeah… you don't have to talk yourself out of being angry right now.",
    ],
    davidFollowUps: [
      "what happened?",
      "has this been building for a while?",
      "yeah… is this about one thing, or has it been piling up?",
      "is this something that's happened before?",
      "is this about one moment, or a pattern with this person?",
      "have you said anything to them about it yet?",
      "what would it look like to actually resolve this?",
      "is it them you're angry at, or more the situation?",
      "how long has this been sitting with you?",
      "did they know it would land like that?",
      "what do you wish had happened instead?",
      "is this the first time, or does it keep happening?",
      "what are you most angry about, if you had to pick one thing?",
      "have you had a chance to cool off, or is it still fresh?",
      "what do you need right now — to vent, or to figure out next steps?",
      "what's the part that's still bothering you the most?",
    ],
    scriptures: [
      {
        reference: 'Ephesians 4:26-27',
        verse: 'In your anger do not sin. Do not let the sun go down while you are still angry, and do not give the devil a foothold.',
        davidIntro: "there's a verse in Ephesians that's interesting because it doesn't tell you not to be angry…",
        davidReflection: "it starts with 'in your anger' — it assumes you're angry. it just says don't let it stay and grow into something that takes root.",
      },
      {
        reference: 'James 1:19-20',
        verse: 'Everyone should be quick to listen, slow to speak and slow to become angry, because human anger does not produce the righteousness that God desires.',
        davidIntro: "James says something about this that's hard to argue with…",
        davidReflection: "slow to anger doesn't mean never angry. it just means — let yourself hear the whole thing first.",
      },
    ],
  },
  {
    key: 'NUMB',
    label: 'Numb',
    davidReaction: [
      "mm… numb is its own kind of heavy. you'd almost rather feel something.",
      "yeah… when you stop feeling, sometimes that's just the mind protecting itself.",
      "man… numb is hard to explain to people. looks fine from the outside.",
      "yeah… sometimes feeling nothing is harder than feeling something.",
      "mm. numb doesn't mean nothing's wrong. sometimes it means a lot is.",
      "yeah… that flat feeling can be its own kind of exhausting.",
      "man, going through the motions without really feeling them is rough.",
      "yeah… sometimes shutting off is just what the mind does to cope for a while.",
      "that disconnect is real, even if it's hard to put into words.",
      "mm… feeling nothing is still feeling something, if that makes sense.",
      "yeah, that gray, far-away feeling is more common than people admit.",
      "man… it's okay that you don't have a neat answer for how you feel.",
      "yeah… sounds like everything's just been on mute for a while.",
      "mm, that's a strange, tiring place to be stuck in.",
      "yeah… I hear you, even in the flatness of it.",
      "man, sometimes numb is the mind's way of buying itself time.",
    ],
    davidFollowUps: [
      "how long has it been like this?",
      "did something happen, or did it just kind of creep in?",
      "yeah… are you still doing the regular things — eating, sleeping?",
      "what was the last thing you felt something about?",
      "did something happen that might've triggered it, or did it creep in slowly?",
      "are you still able to do the regular stuff — work, eating, all that?",
      "when's the last time you felt something, even a little?",
      "does this happen often, or is it new?",
      "is there anything that usually breaks through it?",
      "how long has it felt like this?",
      "are people around you noticing, or does it stay hidden?",
      "is there a specific thing you're avoiding feeling, maybe?",
      "what does a normal day look like for you right now?",
      "do you want to talk about what led up to this?",
      "is sleep affected by any of this?",
      "would it help to just sit here for a minute without trying to figure it out?",
    ],
    scriptures: [
      {
        reference: 'Psalm 42:5',
        verse: 'Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God.',
        davidIntro: "there's a Psalm where the writer is basically talking to himself, asking why he feels so far away…",
        davidReflection: "he doesn't pretend he's fine. he's honest about the distance. and he still says — I will yet praise him. not now. yet.",
      },
      {
        reference: 'Isaiah 43:2',
        verse: 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.',
        davidIntro: "there's a verse in Isaiah about going through hard seasons…",
        davidReflection: "when you pass through — not if. it's assumed you'll go through dark places. the promise is just: not alone.",
      },
    ],
  },
  {
    key: 'CONFUSED',
    label: 'Confused',
    davidReaction: [
      "yeah… sometimes not knowing which way to go is its own kind of stress.",
      "mm… confusion is really disorienting, especially when the stakes feel high.",
      "yeah… being unsure about something important wears on you.",
      "mm, that's a hard spot to be standing in — not knowing which way.",
      "yeah… decisions like that carry a lot of weight when you're unsure.",
      "man, not knowing is sometimes worse than knowing something hard.",
      "yeah, that kind of uncertainty is exhausting in its own way.",
      "mm… sounds like you've been going back and forth on this a lot.",
      "that's a real crossroads. no wonder it's got you stuck.",
      "yeah… wanting clarity and not having it is frustrating.",
      "man, that's a lot to be weighing on your own.",
      "mm, sounds like every option has a downside you're worried about.",
      "yeah… it makes sense you're stuck. this isn't a small decision.",
      "that in-between feeling is rough — not here, not there yet.",
      "mm… I get why you're stuck on this one.",
      "yeah, some decisions just take longer to feel clear. that's not on you.",
    ],
    davidFollowUps: [
      "what's the decision you're sitting with?",
      "yeah… is it a life-direction thing, or something more immediate?",
      "have you talked to anyone you trust about it?",
      "what are the options you're weighing?",
      "what's pulling you toward each direction?",
      "is there a deadline on this, or do you have time to sit with it?",
      "what's your gut telling you, even if your head disagrees?",
      "what's the fear underneath the uncertainty?",
      "is this a decision about direction, or something more immediate?",
      "what would you tell a friend in this same spot?",
      "what's the worst case if you choose wrong?",
      "is it the decision itself, or the not-knowing that's harder?",
      "what's making this one so hard to see clearly?",
      "if you had to decide today, which way would you lean?",
      "what information would actually make this easier to decide?",
      "how long have you been sitting with this one?",
    ],
    scriptures: [
      {
        reference: 'Proverbs 3:5-6',
        verse: 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.',
        davidIntro: "there's a Proverb that people in uncertain seasons come back to a lot…",
        davidReflection: "lean not on your own understanding — that's hard when you want clarity. but sometimes the trust comes before the path gets clear.",
      },
      {
        reference: 'Psalm 119:105',
        verse: 'Your word is a lamp for my feet, a light on my path.',
        davidIntro: "there's a verse about not being able to see the whole road…",
        davidReflection: "a lamp for my feet — not a floodlight for the whole journey. just enough light for the next step. sometimes that's all you get.",
      },
    ],
  },
  {
    key: 'HOPEFUL',
    label: 'Hopeful',
    davidReaction: [
      "yeah… hope is something. especially when things have been hard.",
      "mm… that's good. hold onto that.",
      "yeah… hope has a way of shifting everything slightly.",
      "yeah, that's a good feeling to sit in for a minute.",
      "mm, I like hearing that from you.",
      "yeah… hope after a hard stretch means something.",
      "that's good. don't talk yourself out of it.",
      "mm… that's worth noticing, even if it's small.",
      "yeah, hope's a quiet thing sometimes, but it counts.",
      "man, that's a good shift. glad you're feeling it.",
      "yeah… that little bit of light matters more than people think.",
      "mm, hold onto that feeling. it's real.",
      "yeah… that's a good sign, especially after everything.",
      "that's genuinely good to hear.",
      "mm, I'm glad something's starting to feel lighter.",
      "yeah… that's worth sitting with for a second.",
    ],
    davidFollowUps: [
      "what's making you feel that way?",
      "yeah… something change recently?",
      "that's a good place to be. what's it about?",
      "did something shift, or is it more of a slow build?",
      "how does it feel different from a few weeks ago?",
      "what are you hoping for, specifically?",
      "is this the first time you've felt this in a while?",
      "what would it look like if that hope actually panned out?",
      "what's giving you that feeling right now?",
      "has anything changed recently that's helping?",
      "who else knows you're feeling more hopeful?",
      "what's the thing you're most looking forward to?",
      "does it feel fragile, or pretty solid?",
      "what's different about today?",
      "is there something specific you're holding onto?",
      "what would it take to keep this feeling going?",
    ],
    scriptures: [
      {
        reference: 'Jeremiah 29:11',
        verse: 'For I know the plans I have for you, declares the Lord, plans to give you hope and a future.',
        davidIntro: "there's a verse that was basically written for this feeling…",
        davidReflection: "plans to give you a future and a hope. that's the one people put on their walls — and it earns it.",
      },
    ],
  },
  {
    key: 'GRATEFUL',
    label: 'Grateful',
    davidReaction: [
      "mm… yeah. gratitude has a way of clearing things out a little.",
      "yeah… good. hold onto that.",
      "that's a good thing to feel.",
      "yeah, that's good. gratitude does something to how the rest of the day feels.",
      "mm, I like that. what's on your mind?",
      "yeah… noticing the good stuff matters more than people give it credit for.",
      "that's a good place to be sitting in.",
      "mm… good. tell me more.",
      "yeah, that's worth pausing on for a second.",
      "man, that's a good feeling. glad you've got it.",
      "yeah… gratitude's underrated. glad you're feeling it.",
      "mm, that's genuinely nice to hear.",
      "yeah… good. that's not nothing.",
      "that's a good one to hold onto.",
      "mm, I like hearing that from you.",
      "yeah, that's a good thing to notice today.",
    ],
    davidFollowUps: [
      "what's been the thing you're most grateful for lately?",
      "yeah… did something specific happen?",
      "good to hear. what's been going right?",
      "what's been the biggest thing lately?",
      "did something specific happen, or is it more general?",
      "who's part of that gratitude, if anyone?",
      "how long has this feeling been sticking around?",
      "what's different about how you're seeing things today?",
      "is this a new thing, or does it come and go?",
      "what would you want to remember about this feeling later?",
      "what's the small thing that made the biggest difference?",
      "who would you want to tell about this?",
      "does it feel like a shift, or just a good day?",
      "what's one thing you're thankful for today, specifically?",
      "how are you planning to hold onto this feeling?",
      "what sparked it?",
    ],
    scriptures: [
      {
        reference: '1 Thessalonians 5:18',
        verse: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.",
        davidIntro: "there's a verse about this that's short but it's got some weight to it…",
        davidReflection: "in all circumstances. not just the good ones. that's harder than it sounds — but when you can do it, it really does change how things feel.",
      },
    ],
  },
  {
    key: 'JOYFUL',
    label: 'Joyful',
    davidReaction: [
      "mm… yeah. good.",
      "yeah… that kind of joy is worth sitting in for a minute.",
      "man, that's good to hear.",
      "yeah! that's great, actually.",
      "mm, I love that. tell me more.",
      "yeah… that's the good stuff right there.",
      "man, I'm smiling just hearing that.",
      "that's awesome, honestly.",
      "yeah, that's a great feeling to have today.",
      "mm, that's really good to hear.",
      "yeah… hold onto that one, it's a good one.",
      "man, that's exactly the kind of thing worth celebrating.",
      "yeah, that's great! what happened?",
      "mm, I'm genuinely happy for you.",
      "yeah… that's a good one. enjoy it.",
      "man, that's the best kind of news.",
    ],
    davidFollowUps: [
      "what's been happening?",
      "yeah… what made the difference?",
      "good. what's it about?",
      "what happened?!",
      "who else knows yet?",
      "how are you celebrating?",
      "did you see this coming, or total surprise?",
      "what's the best part about it?",
      "how long have you been waiting for this?",
      "what's next for you now?",
      "who do you want to tell first?",
      "how does it feel, now that it's real?",
      "what made today the day it happened?",
      "is this the kind of thing you've been hoping for a while?",
      "what are you most excited about?",
      "how are you feeling right now, in this moment?",
    ],
    scriptures: [
      {
        reference: 'Nehemiah 8:10',
        verse: 'Do not grieve, for the joy of the Lord is your strength.',
        davidIntro: "there's a line in Nehemiah that I think about when things are actually going well…",
        davidReflection: "the joy of the Lord is your strength. not a nice feeling — strength. something to stand on.",
      },
    ],
  },
  {
    key: 'PEACEFUL',
    label: 'Peaceful',
    davidReaction: [
      "mm… peace is something. especially if things have been hard.",
      "yeah… that's good. peace is harder to come by than people think.",
      "yeah, that's a good place to be sitting in.",
      "mm, I'm glad you're feeling that.",
      "yeah… peace after a hard stretch means something real.",
      "that's good. hold onto that feeling.",
      "mm, that's genuinely nice to hear.",
      "yeah… quiet like that is worth noticing.",
      "man, that's a good place to be.",
      "yeah, peace is underrated. glad you've got some.",
      "mm… that sounds like a good headspace.",
      "yeah, that's worth sitting in for a minute.",
      "that's a good sign, honestly.",
      "mm, I like hearing that things feel settled.",
      "yeah… that calm is well earned, probably.",
      "man, that's good. glad it's landed on you today.",
    ],
    davidFollowUps: [
      "yeah… what's been making you feel peaceful?",
      "that's a good place. what shifted?",
      "what's helping you feel that way?",
      "did something shift, or has it been building?",
      "how long has it felt like this?",
      "what's different about today?",
      "is this a new feeling, or does it come and go?",
      "what usually gets you to this place?",
      "does it feel steady, or more like a passing moment?",
      "what would you want to remember about this feeling?",
      "how are you planning to hold onto it?",
      "what's contributing to it the most?",
      "is there anything you're doing differently?",
      "what's it like compared to how you usually feel?",
      "who else is part of this peace, if anyone?",
      "what's the quiet like right now?",
    ],
    scriptures: [
      {
        reference: 'John 14:27',
        verse: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.',
        davidIntro: "Jesus said something about peace that's different from the way the world uses that word…",
        davidReflection: "not as the world gives. the world's peace depends on things going well. this one is something underneath everything else.",
      },
    ],
  },
];

/** Returns a random scripture with full David delivery metadata for a given mood. */
export function getScriptureForMood(moodKey: string): Scripture | null {
  const mood = MOODS_DATA.find(m => m.key === moodKey.toUpperCase());
  if (!mood?.scriptures.length) return null;
  return mood.scriptures[Math.floor(Math.random() * mood.scriptures.length)];
}

/** Returns a random David reaction line for a given mood. */
export function getDavidReactionForMood(moodKey: string): string | null {
  const mood = MOODS_DATA.find(m => m.key === moodKey.toUpperCase());
  if (!mood?.davidReaction.length) return null;
  return mood.davidReaction[Math.floor(Math.random() * mood.davidReaction.length)];
}

/** Returns a random follow-up question David asks after sharing scripture. */
export function getDavidFollowUpForMood(moodKey: string): string | null {
  const mood = MOODS_DATA.find(m => m.key === moodKey.toUpperCase());
  if (!mood?.davidFollowUps.length) return null;
  return mood.davidFollowUps[Math.floor(Math.random() * mood.davidFollowUps.length)];
}

/**
 * Builds a complete David scripture response block for a mood.
 * Use this to inject into system context or pre-populate responses.
 */
export function buildDavidScriptureResponse(moodKey: string): string | null {
  const mood = MOODS_DATA.find(m => m.key === moodKey.toUpperCase());
  if (!mood?.scriptures.length || !mood.davidFollowUps.length) return null;
  const scripture = mood.scriptures[Math.floor(Math.random() * mood.scriptures.length)];
  const followUp = mood.davidFollowUps[Math.floor(Math.random() * mood.davidFollowUps.length)];
  if (!scripture || !followUp) return null;
  const bookName = scripture.reference.split(' ')[0];
  return [
    scripture.davidIntro,
    `'${scripture.verse}'`,
    `that's from ${bookName}. ${scripture.davidReflection}`,
    followUp,
  ].join('\n\n');
}
